"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, ChevronDown, ChevronUp, HelpCircle, FileText, Mic, Shield, CreditCard, Key } from "lucide-react";

interface HelpCenterModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const FAQS = [
  {
    category: "Getting Started",
    Icon: Shield,
    items: [
      {
        q: "What is VeriGuard AI?",
        a: "VeriGuard AI is an AI content detection platform that analyzes text and audio files to determine whether they were generated by AI or synthetic voice systems. Every result includes explainable insights so you understand the reasoning behind each verdict.",
      },
      {
        q: "Do I need an account to use it?",
        a: "No — you can use the interactive demo directly on the homepage without signing up. Creating an account unlocks higher usage limits, PDF report exports, and history.",
      },
    ],
  },
  {
    category: "Text Detection",
    Icon: FileText,
    items: [
      {
        q: "What kind of text can I analyze?",
        a: "You can paste or type any text content — essays, articles, emails, social media posts, academic work, etc. The platform supports plain text and will analyze up to 5,000 characters per submission on the free tier.",
      },
      {
        q: "How accurate is text detection?",
        a: "The DeBERTa-v3 ensemble model achieves over 96% detection accuracy on our benchmark datasets. Accuracy can vary depending on text length and writing style — longer passages generally yield more reliable results.",
      },
    ],
  },
  {
    category: "Voice Detection",
    Icon: Mic,
    items: [
      {
        q: "What audio formats are supported?",
        a: "The platform accepts .wav and .mp3 files. For best results, use recordings that are at least 3 seconds long with minimal background noise.",
      },
      {
        q: "How does voice detection work?",
        a: "We use a 4-branch adaptive fusion model (AASIST + WavLM-Large + Spectral + Physiological branches) that analyzes multiple aspects of an audio signal simultaneously to detect synthesis artifacts.",
      },
    ],
  },
  {
    category: "Billing & Plans",
    Icon: CreditCard,
    items: [
      {
        q: "Is the Starter plan really free?",
        a: "Yes, entirely. The Starter plan is free forever and includes 50 text checks and 10 voice uploads per month. No credit card required.",
      },
      {
        q: "Can I cancel my Pro plan anytime?",
        a: "Absolutely. You can cancel at any time from your account settings. Your plan remains active until the end of your billing period.",
      },
    ],
  },
  {
    category: "Privacy & Security",
    Icon: Key,
    items: [
      {
        q: "Is my content stored after analysis?",
        a: "No. Content submitted through the demo or detection pages is processed in-memory and not persisted. Account users can optionally enable history, but this is opt-in only.",
      },
      {
        q: "Is the platform GDPR compliant?",
        a: "Yes. We follow data minimization principles and do not store personal content. You can request deletion of any account data at any time by contacting us.",
      },
    ],
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderBottom: "1px solid var(--border)" }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between",
          padding: "14px 0", background: "none", border: "none", cursor: "pointer",
          textAlign: "left", gap: 12,
        }}
      >
        <span style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)", fontFamily: "var(--font-body)", lineHeight: 1.5 }}>{q}</span>
        {open ? <ChevronUp size={14} color="var(--accent)" style={{ flexShrink: 0 }} /> : <ChevronDown size={14} color="var(--text-muted)" style={{ flexShrink: 0 }} />}
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }} style={{ overflow: "hidden" }}
          >
            <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.75, fontFamily: "var(--font-body)", paddingBottom: 14 }}>{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export function HelpCenterModal({ isOpen, onClose }: HelpCenterModalProps) {
  const [activeCategory, setActiveCategory] = useState(0);

  useEffect(() => {
    if (isOpen) document.body.style.overflow = "hidden";
    else document.body.style.overflow = "";
    return () => { document.body.style.overflow = ""; };
  }, [isOpen]);

  useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", h);
    return () => document.removeEventListener("keydown", h);
  }, [onClose]);

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            key="help-backdrop"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            onClick={onClose}
            style={{ position: "fixed", inset: 0, zIndex: 200, background: "rgba(26,26,46,0.5)", backdropFilter: "blur(6px)", WebkitBackdropFilter: "blur(6px)" }}
          />
          <div style={{ position: "fixed", inset: 0, zIndex: 201, display: "flex", alignItems: "center", justifyContent: "center", padding: 16, pointerEvents: "none" }}>
            <motion.div
              id="help-modal"
              role="dialog" aria-modal="true" aria-labelledby="help-modal-title"
              initial={{ opacity: 0, scale: 0.94, y: 16 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.94, y: 16 }}
              transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] as any }}
              style={{ width: "100%", maxWidth: 680, background: "#fff", borderRadius: 24, border: "1px solid var(--border)", boxShadow: "0 24px 64px rgba(0,0,0,0.12)", overflow: "hidden", position: "relative", pointerEvents: "auto", maxHeight: "88vh", display: "flex", flexDirection: "column" }}
            >
              {/* Header */}
              <div style={{ padding: "28px 32px 20px", borderBottom: "1px solid var(--border)", flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                  <div style={{ width: 38, height: 38, borderRadius: 10, background: "var(--accent-light)", border: "1px solid var(--border-accent)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <HelpCircle size={18} color="var(--accent)" />
                  </div>
                  <div>
                    <h2 id="help-modal-title" style={{ fontSize: 18, fontWeight: 800, color: "var(--text-primary)", fontFamily: "var(--font-heading)", letterSpacing: "-0.01em" }}>Help Center</h2>
                    <p style={{ fontSize: 12, color: "var(--text-muted)", fontFamily: "var(--font-body)" }}>Frequently asked questions</p>
                  </div>
                </div>
                <button
                  onClick={onClose} aria-label="Close"
                  style={{ width: 30, height: 30, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--bg-surface)", border: "1px solid var(--border)", cursor: "pointer" }}
                  onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = "var(--accent-light)"; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = "var(--bg-surface)"; }}
                >
                  <X size={14} color="var(--text-secondary)" />
                </button>
              </div>

              {/* Body — sidebar + content */}
              <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>
                {/* Category sidebar */}
                <div style={{ width: 180, borderRight: "1px solid var(--border)", padding: "16px 12px", flexShrink: 0, display: "flex", flexDirection: "column", gap: 4, overflowY: "auto", background: "var(--bg-surface)" }}>
                  {FAQS.map((cat, i) => (
                    <button
                      key={cat.category}
                      onClick={() => setActiveCategory(i)}
                      style={{
                        display: "flex", alignItems: "center", gap: 8, padding: "9px 10px",
                        borderRadius: 8, border: "none", cursor: "pointer", textAlign: "left",
                        background: activeCategory === i ? "var(--accent-light)" : "transparent",
                        color: activeCategory === i ? "var(--accent)" : "var(--text-secondary)",
                        fontSize: 12, fontWeight: activeCategory === i ? 600 : 500,
                        transition: "all 0.15s", fontFamily: "var(--font-body)",
                      }}
                      onMouseEnter={e => { if (activeCategory !== i) (e.currentTarget as HTMLButtonElement).style.background = "rgba(0,0,0,0.04)"; }}
                      onMouseLeave={e => { if (activeCategory !== i) (e.currentTarget as HTMLButtonElement).style.background = "transparent"; }}
                    >
                      <cat.Icon size={13} />
                      {cat.category}
                    </button>
                  ))}
                </div>

                {/* FAQ list */}
                <div style={{ flex: 1, padding: "20px 28px", overflowY: "auto" }}>
                  <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, fontFamily: "var(--font-heading)" }}>
                    {FAQS[activeCategory].category}
                  </div>
                  {FAQS[activeCategory].items.map(item => (
                    <FAQItem key={item.q} q={item.q} a={item.a} />
                  ))}
                </div>
              </div>
            </motion.div>
          </div>
        </>
      )}
    </AnimatePresence>
  );
}
