"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Activity, FileText, Mic, TrendingUp, CheckCircle,
  Eye, BarChart2, X, Download, AlertTriangle,
} from "lucide-react";

/* ── Mock data ──────────────────────────────────────────────────────────── */
const SUMMARY_CARDS = [
  { label: "Total Analyses",  value: 47, Icon: Activity,    trend: "+12 this week",  sub: "All checks combined"    },
  { label: "Text Analyses",   value: 31, Icon: FileText,    trend: "+8 this week",   sub: "Written content checks" },
  { label: "Voice Analyses",  value: 16, Icon: Mic,         trend: "+4 this week",   sub: "Audio file checks"      },
  { label: "AI Detected",     value: 38, Icon: TrendingUp,  trend: "81% detection",  sub: "Flagged as AI-generated"},
  { label: "Likely Human",    value: 9,  Icon: CheckCircle, trend: "19% detection",  sub: "Passed as genuine"      },
];

const RECENT = [
  { id: 1, time: "Today, 2:14 PM",     type: "Text",  name: "essay_draft.txt",     preview: "The algorithmic progression of...", result: "AI Generated",    confidence: 96.3, ai: true  },
  { id: 2, time: "Today, 11:32 AM",    type: "Voice", name: "interview_clip.wav",  preview: "wav · 4.2 MB",                      result: "Synthetic Voice", confidence: 90.2, ai: true  },
  { id: 3, time: "Yesterday, 4:07 PM", type: "Text",  name: "research_paper.txt",  preview: "In this study, we examine...",       result: "Likely Human",    confidence: 22.1, ai: false },
  { id: 4, time: "Yesterday, 1:55 PM", type: "Voice", name: "podcast_excerpt.mp3", preview: "mp3 · 11.7 MB",                     result: "Synthetic Voice", confidence: 87.6, ai: true  },
  { id: 5, time: "May 10, 10:20 AM",   type: "Text",  name: "blog_post.txt",       preview: "There has never been a better...",   result: "Likely Human",    confidence: 18.4, ai: false },
  { id: 6, time: "May 9, 3:44 PM",     type: "Voice", name: "voicemail.wav",       preview: "wav · 2.1 MB",                      result: "Synthetic Voice", confidence: 94.1, ai: true  },
];

const TREND = [5, 8, 3, 11, 7, 14, 9, 17, 12, 19, 16, 23];
const TREND_LABELS = ["Apr 30","May 1","May 2","May 3","May 4","May 5","May 6","May 7","May 8","May 9","May 10","May 11"];

type ReportEntry = typeof RECENT[0];

function getReportDetails(r: ReportEntry) {
  if (r.type === "Text") {
    return {
      explanation: "This text was marked as AI-likely because it uses very even sentence structure, repeated formal wording, and low variation in writing style. The word choices appear unusually consistent — a pattern rarely seen in genuine human writing.",
      highlights: [
        "Unusually consistent sentence length (94% confidence)",
        "Uncommon word frequency distribution (82% confidence)",
        "Low text complexity and emotional variation (76% confidence)",
      ],
    };
  }
  return {
    explanation: "This voice recording shows signs of synthesis. The audio contains spectral artifacts typical of text-to-speech models, and the pitch patterns do not match natural human voice characteristics.",
    highlights: [
      "Unnatural pitch variation at 01.20s – 02.10s (87% confidence)",
      "Spectral artifacts consistent with TTS output (79% confidence)",
      "Breath pattern inconsistencies detected (73% confidence)",
    ],
  };
}

function downloadReport(r: ReportEntry) {
  const d = getReportDetails(r);
  const lines = [
    "VeriGuard AI — Analysis Report",
    "================================",
    `Date:       ${r.time}`,
    `Type:       ${r.type}`,
    `File:       ${r.name}`,
    `Result:     ${r.result}`,
    `Confidence: ${r.confidence}%`,
    "",
    "Summary",
    "-------",
    d.explanation,
    "",
    "Key Signals",
    "-----------",
    ...d.highlights.map(h => `• ${h}`),
    "",
    "Generated by VeriGuard AI — veriguard.ai",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url;
  a.download = `veriguard-report-${r.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ── Helpers ────────────────────────────────────────────────────────────── */
const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 14 },
  animate: { opacity: 1, y: 0, transition: { delay, duration: 0.45, ease: [0.22, 1, 0.36, 1] as any } },
});

/* ── Trend bar chart ────────────────────────────────────────────────────── */
function TrendChart() {
  const max = Math.max(...TREND);
  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-end", gap: 4, height: 80, marginBottom: 6 }}>
        {TREND.map((v, i) => (
          <motion.div
            key={i}
            initial={{ height: 0 }}
            animate={{ height: (v / max) * 80 }}
            transition={{ delay: i * 0.04, duration: 0.5, ease: [0.22, 1, 0.36, 1] as any }}
            style={{
              flex: 1, borderRadius: "3px 3px 0 0",
              background: i === TREND.length - 1 ? "var(--accent)" : "#C4B5FD",
              opacity: i === TREND.length - 1 ? 1 : 0.75,
              minWidth: 0,
            }}
          />
        ))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 9, color: "var(--text-muted)", fontFamily: "var(--font-mono)" }}>
        {TREND_LABELS.map((l, i) => (
          <span key={l} style={{ opacity: i % 3 === 0 ? 1 : 0 }}>{l.split(" ")[1]}</span>
        ))}
      </div>
    </div>
  );
}

/* ── Distribution donut ─────────────────────────────────────────────────── */
function DistributionChart() {
  const total = 47;
  const aiPct = 38 / total;
  const r = 34;
  const circ = 2 * Math.PI * r;
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
      <div style={{ position: "relative", flexShrink: 0 }}>
        <svg width="88" height="88" viewBox="0 0 88 88" style={{ transform: "rotate(-90deg)" }}>
          <circle cx="44" cy="44" r={r} fill="none" stroke="var(--border)" strokeWidth="13" />
          <motion.circle cx="44" cy="44" r={r} fill="none" stroke="#C4B5FD" strokeWidth="13" strokeDasharray={circ} strokeDashoffset={0} />
          <motion.circle
            cx="44" cy="44" r={r} fill="none" stroke="var(--accent)" strokeWidth="13"
            strokeLinecap="round" strokeDasharray={circ}
            initial={{ strokeDashoffset: circ }}
            animate={{ strokeDashoffset: circ - circ * aiPct }}
            transition={{ duration: 1.2, ease: "easeOut" }}
          />
        </svg>
        <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
          <div className="mono" style={{ fontSize: 15, fontWeight: 800, color: "var(--accent)", lineHeight: 1 }}>{Math.round(aiPct * 100)}%</div>
          <div style={{ fontSize: 8, color: "var(--text-muted)", marginTop: 2 }}>AI</div>
        </div>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 9 }}>
        {[
          { color: "var(--accent)", label: "AI Generated", count: 38 },
          { color: "#C4B5FD",       label: "Likely Human",  count: 9  },
        ].map(d => (
          <div key={d.label} style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{ width: 9, height: 9, borderRadius: 2, background: d.color, flexShrink: 0 }} />
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: "var(--text-primary)" }}>{d.label}</div>
              <div style={{ fontSize: 10, color: "var(--text-muted)" }}>{d.count} detections</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ── Text vs Voice chart ─────────────────────────────────────────────────── */
function TypeBreakdownChart() {
  const data = [
    { label: "Text Analyses",  count: 31, pct: 66 },
    { label: "Voice Analyses", count: 16, pct: 34 },
  ];
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {data.map((d, i) => (
        <div key={d.label}>
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 6 }}>
            <span style={{ color: "var(--text-secondary)", fontWeight: 500 }}>{d.label}</span>
            <span className="mono" style={{ fontWeight: 700, color: "var(--text-primary)" }}>{d.count} <span style={{ color: "var(--text-muted)", fontWeight: 400 }}>({d.pct}%)</span></span>
          </div>
          <div className="progress-track" style={{ height: 7, borderRadius: 999 }}>
            <motion.div
              className="progress-fill progress-indigo"
              initial={{ width: 0 }}
              animate={{ width: `${d.pct}%` }}
              transition={{ delay: 0.1 + i * 0.1, duration: 0.9, ease: "easeOut" }}
              style={{ borderRadius: 999, opacity: i === 1 ? 0.6 : 1 }}
            />
          </div>
        </div>
      ))}
      <div style={{ borderTop: "1px solid var(--border)", paddingTop: 12, marginTop: 2 }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "var(--text-muted)" }}>
          <span>Total: 47 analyses</span>
          <span>Last 12 days</span>
        </div>
      </div>
    </div>
  );
}

/* ── Report Modal ────────────────────────────────────────────────────────── */
function ReportModal({ report, onClose }: { report: ReportEntry | null; onClose: () => void }) {
  if (!report) return null;
  const details = getReportDetails(report);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      style={{
        position: "fixed", inset: 0, zIndex: 300,
        background: "rgba(9,9,11,0.5)", backdropFilter: "blur(4px)",
        display: "flex", alignItems: "center", justifyContent: "center",
        padding: 20,
      }}
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, y: 20, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: 12, scale: 0.97 }}
        transition={{ duration: 0.2, ease: [0.22, 1, 0.36, 1] as any }}
        onClick={e => e.stopPropagation()}
        style={{
          background: "#fff", borderRadius: 14, border: "1px solid var(--border)",
          maxWidth: 560, width: "100%", overflow: "hidden",
        }}
      >
        {/* Header */}
        <div style={{ padding: "16px 20px", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div>
            <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text-primary)", fontFamily: "var(--font-heading)" }}>
              Analysis Report
            </div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 2 }}>{report.time}</div>
          </div>
          <button
            onClick={onClose}
            style={{ width: 28, height: 28, borderRadius: 7, border: "1px solid var(--border)", background: "transparent", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text-muted)", transition: "all 0.12s" }}
            onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--accent)"; (e.currentTarget as HTMLButtonElement).style.color = "var(--accent)"; }}
            onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--border)"; (e.currentTarget as HTMLButtonElement).style.color = "var(--text-muted)"; }}
          >
            <X size={13} />
          </button>
        </div>

        {/* Body */}
        <div style={{ padding: 20 }}>
          {/* Type + Result badges */}
          <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
            <span className="badge badge-neutral">
              {report.type === "Text" ? <FileText size={10} /> : <Mic size={10} />}
              {report.type}
            </span>
            <span style={{
              display: "inline-flex", alignItems: "center", gap: 5, padding: "3px 10px", borderRadius: 6,
              fontSize: 11, fontWeight: 600, border: "1px solid",
              background: report.ai ? "var(--accent-light)" : "var(--bg-surface)",
              color: report.ai ? "var(--accent)" : "var(--text-secondary)",
              borderColor: report.ai ? "var(--border-accent)" : "var(--border)",
            }}>
              {report.result}
            </span>
          </div>

          {/* File + Confidence */}
          <div style={{ background: "var(--bg-surface)", borderRadius: 10, padding: "12px 16px", marginBottom: 16, border: "1px solid var(--border)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div>
              <div style={{ fontSize: 12, fontWeight: 700, color: "var(--text-primary)", marginBottom: 2 }}>{report.name}</div>
              <div style={{ fontSize: 11, color: "var(--text-muted)" }}>{report.preview}</div>
            </div>
            <div style={{ textAlign: "right", flexShrink: 0 }}>
              <div className="mono" style={{ fontSize: 22, fontWeight: 900, color: "var(--accent)", lineHeight: 1 }}>{report.confidence}%</div>
              <div style={{ fontSize: 10, color: "var(--text-muted)", marginTop: 2 }}>Confidence</div>
            </div>
          </div>

          {/* Explanation summary */}
          <div style={{ marginBottom: 14 }}>
            <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-primary)", fontFamily: "var(--font-heading)", marginBottom: 8 }}>
              Explanation Summary
            </div>
            <div style={{
              background: "var(--accent-light)", border: "1px solid var(--border-accent)",
              borderRadius: 8, padding: "12px 14px",
            }}>
              <p style={{ fontSize: 12, color: "var(--text-primary)", lineHeight: 1.75, margin: 0 }}>{details.explanation}</p>
            </div>
          </div>

          {/* Key signals / highlights */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-primary)", fontFamily: "var(--font-heading)", marginBottom: 8 }}>
              {report.type === "Text" ? "Important Highlights" : "Suspicious Sections"}
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {details.highlights.map((h, i) => (
                <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 10, background: "var(--bg-surface)", borderRadius: 8, padding: "10px 12px", border: "1px solid var(--border)" }}>
                  <AlertTriangle size={12} color="var(--accent)" style={{ flexShrink: 0, marginTop: 1 }} />
                  <span style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>{h}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div style={{ padding: "14px 20px", borderTop: "1px solid var(--border)", display: "flex", gap: 8, justifyContent: "flex-end" }}>
          <button onClick={onClose} className="btn-ghost" style={{ fontSize: 13 }}>Close</button>
          <button
            onClick={() => downloadReport(report)}
            className="btn-primary"
            style={{ fontSize: 13, padding: "8px 18px" }}
          >
            <Download size={13} /> Download Report
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}

/* ── Main Export ────────────────────────────────────────────────────────── */
export function DashboardPage({
  onTextStart,
  onVoiceStart,
}: {
  onTextStart: () => void;
  onVoiceStart: () => void;
}) {
  const [selectedReport, setSelectedReport] = useState<ReportEntry | null>(null);

  return (
    <>
      <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
        {/* Header */}
        <motion.div {...fadeUp()}>
          <div className="section-label" style={{ marginBottom: 6 }}>Overview</div>
          <h1 style={{ fontSize: 28, fontWeight: 800, color: "var(--text-primary)", letterSpacing: "-0.02em", fontFamily: "var(--font-heading)" }}>
            Dashboard
          </h1>
          <p style={{ fontSize: 13, color: "var(--text-secondary)", marginTop: 6 }}>
            Your analysis history and detection summary.
          </p>
        </motion.div>

        {/* Summary cards */}
        <motion.div {...fadeUp(0.04)}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 12 }}>
            {SUMMARY_CARDS.map((c, i) => (
              <motion.div
                key={c.label}
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.04 + i * 0.06, duration: 0.4 }}
                className="card" style={{ padding: "20px 16px" }}
              >
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}>
                  <div style={{ width: 34, height: 34, borderRadius: 9, background: "var(--accent-light)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <c.Icon size={15} color="var(--accent)" />
                  </div>
                </div>
                <div className="mono" style={{ fontSize: 28, fontWeight: 900, color: "var(--text-primary)", lineHeight: 1, marginBottom: 5 }}>{c.value}</div>
                <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-primary)", fontFamily: "var(--font-heading)", marginBottom: 3 }}>{c.label}</div>
                <div style={{ fontSize: 11, color: "var(--text-muted)" }}>{c.trend}</div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Charts row */}
        <motion.div {...fadeUp(0.1)} style={{ display: "grid", gridTemplateColumns: "1.8fr 1fr 1fr", gap: 14 }}>
          {/* Trend */}
          <div className="glass" style={{ padding: 22 }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }}>
              <div>
                <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", fontFamily: "var(--font-heading)" }}>Weekly Analysis Activity</div>
                <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 2 }}>Analyses over the last 12 days</div>
              </div>
              <span className="badge badge-violet"><BarChart2 size={10} /> Last 12 days</span>
            </div>
            <TrendChart />
          </div>

          {/* Distribution */}
          <div className="glass" style={{ padding: 22 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", fontFamily: "var(--font-heading)", marginBottom: 3 }}>Result Distribution</div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", marginBottom: 18 }}>AI vs. human across all checks</div>
            <DistributionChart />
          </div>

          {/* Text vs Voice */}
          <div className="glass" style={{ padding: 22 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", fontFamily: "var(--font-heading)", marginBottom: 3 }}>Text vs Voice Usage</div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", marginBottom: 18 }}>Breakdown by analysis type</div>
            <TypeBreakdownChart />
          </div>
        </motion.div>

        {/* Recent activity */}
        <motion.div {...fadeUp(0.14)}>
          <div className="glass" style={{ padding: 0, overflow: "hidden" }}>
            <div style={{ padding: "16px 20px", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", fontFamily: "var(--font-heading)" }}>Recent Activity</div>
              <span className="badge badge-neutral">{RECENT.length} entries</span>
            </div>

            <div style={{ overflowX: "auto" }}>
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr style={{ background: "var(--bg-surface)" }}>
                    {["Date / Time", "Type", "File / Content", "Result", "Confidence", "Action"].map(h => (
                      <th key={h} style={{ padding: "10px 16px", textAlign: "left", fontSize: 11, fontWeight: 600, color: "var(--text-muted)", letterSpacing: "0.05em", textTransform: "uppercase", fontFamily: "var(--font-heading)", whiteSpace: "nowrap", borderBottom: "1px solid var(--border)" }}>
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {RECENT.map((r, i) => (
                    <motion.tr
                      key={r.id}
                      initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                      transition={{ delay: 0.18 + i * 0.04 }}
                      style={{ borderBottom: "1px solid var(--border)" }}
                    >
                      <td style={{ padding: "12px 16px", fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" }}>{r.time}</td>
                      <td style={{ padding: "12px 16px" }}>
                        <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                          {r.type === "Text" ? <FileText size={12} color="var(--accent)" /> : <Mic size={12} color="var(--accent)" />}
                          <span style={{ fontSize: 12, fontWeight: 600, color: "var(--text-primary)" }}>{r.type}</span>
                        </div>
                      </td>
                      <td style={{ padding: "12px 16px", maxWidth: 200 }}>
                        <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-primary)", marginBottom: 2 }}>{r.name}</div>
                        <div style={{ fontSize: 11, color: "var(--text-muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.preview}</div>
                      </td>
                      <td style={{ padding: "12px 16px" }}>
                        <span style={{
                          display: "inline-flex", alignItems: "center", padding: "3px 9px", borderRadius: 6,
                          fontSize: 11, fontWeight: 600, fontFamily: "var(--font-body)",
                          background: r.ai ? "var(--accent-light)" : "var(--bg-surface)",
                          color: r.ai ? "var(--accent)" : "var(--text-secondary)",
                          border: `1px solid ${r.ai ? "var(--border-accent)" : "var(--border)"}`,
                        }}>
                          {r.result}
                        </span>
                      </td>
                      <td style={{ padding: "12px 16px" }}>
                        <span className="mono" style={{ fontSize: 12, fontWeight: 700, color: r.ai ? "var(--accent)" : "var(--text-secondary)" }}>{r.confidence}%</span>
                      </td>
                      <td style={{ padding: "12px 16px" }}>
                        <button
                          onClick={() => setSelectedReport(r)}
                          style={{
                            display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, padding: "5px 10px",
                            borderRadius: 6, background: "transparent", border: "1px solid var(--border)",
                            color: "var(--text-secondary)", cursor: "pointer", fontFamily: "var(--font-body)", transition: "all 0.12s",
                          }}
                          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--accent)"; (e.currentTarget as HTMLButtonElement).style.color = "var(--accent)"; (e.currentTarget as HTMLButtonElement).style.background = "var(--accent-light)"; }}
                          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--border)"; (e.currentTarget as HTMLButtonElement).style.color = "var(--text-secondary)"; (e.currentTarget as HTMLButtonElement).style.background = "transparent"; }}
                        >
                          <Eye size={11} /> View Report
                        </button>
                      </td>
                    </motion.tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </motion.div>

        {/* Quick actions */}
        <motion.div {...fadeUp(0.2)}>
          <div className="section-label" style={{ marginBottom: 12 }}>Quick Actions</div>
          <div style={{ display: "flex", gap: 10 }}>
            <button onClick={onTextStart} className="btn-primary">
              <FileText size={14} /> Analyze Text
            </button>
            <button onClick={onVoiceStart} className="btn-secondary">
              <Mic size={14} /> Analyze Voice
            </button>
            <button
              onClick={() => RECENT[0] && setSelectedReport(RECENT[0])}
              className="btn-ghost"
            >
              <Eye size={14} /> View Reports
            </button>
          </div>
        </motion.div>
      </div>

      {/* Report details modal */}
      <AnimatePresence>
        {selectedReport && (
          <ReportModal report={selectedReport} onClose={() => setSelectedReport(null)} />
        )}
      </AnimatePresence>
    </>
  );
}
